<?php
/**
 * @file
 * Code for the JPEC News feature.
 */

include_once 'jpec_news.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 * Open the summary field by default.
 */
function jpec_news_form_news_node_form_alter(&$form, &$form_state, $form_id) {

  // Expose the summary and make it required
    if ($form_id == "news_node_form") {
      $form['field_news_body'][LANGUAGE_NONE][0]['summary']['#required'] = TRUE;
      $script = 'jQuery(document).ready(function(){ jQuery(".link-edit-summary").click(); });';
      drupal_add_js($script, 'inline');
    }
  }
