<?php
/**
 * @file
 * Theme and preprocess functions for panels and panes.
 */
function jpec_preprocess_panels_pane(&$vars) {
  
  //dpm($vars['content']['#bundle'],'bundle');

  // switch ($vars['content']['#bundle']) {
      
  //     case 'homepage_panes':
  //       dpm($vars, 'all vars from panel homepage');
  //       dpm($vars['content']['field_header_image_tall'],'img from panel');
  //       $vraiables['header_image_tall'] = $vars['content']['field_header_image_tall'];
  //       // if (!empty($variables['paragraphs_item']->field_text_area_style)) {
  //       //   $variables['classes_array'][] = $variables['paragraphs_item']->field_text_area_style[LANGUAGE_NONE][0]['value'];
  //       // }
  //       break;

  //       default:
  //       break;
  // }


  //dpm($vars['content']['field_header_image_tall']);
  //$variables[$header_image_tall]
  //$vars['header_image_tall'] = $vars['content']['field_header_image_tall'];
}