<?php
/**
 * @file
 * Code for the JPEC Paragraphs feature.
 */

include_once 'jpec_paragraphs.features.inc';

/**
 * Implements hook_field_widget_form_alter().
 */
function jpec_paragraphs_field_widget_form_alter(&$element, &$form_state, $context) {

  switch ($context['field']['field_name']) {
    
    // Story Reference view
    case 'field_story_view':
      // Do not show the view name selector.
      $element['vname']['#access'] = FALSE;

      // Use title and description from vname on vargs.
      $element['vargs']['#title'] = $element['vname']['#title'];
      $element['vargs']['#description'] = $element['vname']['#description'];
      $element['vargs']['#required'] = TRUE;

      // Disable the token options.
      $element['token_help']['#access'] = FALSE;
      break;            
    
    default:
      break;
  }

}

/**
 * Implements hook_classy_paragraphs_list_options().
 */
function jpec_paragraphs_classy_paragraphs_list_options($options, $field, $instance) {
  if ($field['field_name'] == 'field_paragraph_container_style') {
    $options['background-gold'] = t('Gold Background');
    $options['background-blue-line'] = t('Blue Background');
    $options['background-grey'] = t('Grey Background');
  }

  return $options;
}

/**
 * Implements template_preprocess_field().
 */
function jpec_paragraphs_preprocess_field(&$variables) {

  // add javascript for Facebook
  if (isset($variables['element']['#field_name']) && $variables['element']['#field_name'] == 'field_facebook_page_name') {
    drupal_add_js(drupal_get_path('module', 'jpec_paragraphs') . '/js/facebook-widget.js');
  }

  // add javascript for Twitter
  if (isset($variables['element']['#field_name']) && $variables['element']['#field_name'] == 'field_twitter_username') {
    drupal_add_js(drupal_get_path('module', 'jpec_paragraphs') . '/js/twitter-widget.js');
  }
}
